server:
  port: 7443
  http2:
    enabled: true
  ssl:
    enabled: false
#    key-store: classpath:./certs/localhost.p12
#    key-store-type: PKCS12
#    key-store-password: changeit
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 10240

# Jwt
springbootwebfluxjjwt:
  password:
    encoder:
      secret: mysecret
      iteration: 33
      keylength: 256
  jjwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 28800

logging:
  level:
    com.reactive: TRACE
    root: DEBUG # default is INFO
    org.hibernate: DEBUG


